### ISSUE TITLE
Any documentation on how to include this using gradle?

### ISSUE THREAD

**Issue by jatinhariani** [crowjdh/Snacktory_Android#1]
I did the following:
Downloaded and put the slf4j-android-1.6.1-RC1.jar in the app/libs folder.

My Gradle dependency looks like:

```
    dependencies {
        compile 'com.android.support:appcompat-v7:22.1.1'
        compile 'com.mcxiaoke.volley:library-aar:1.0.0'
        files('slf4j-android-1.6.1-RC1.jar')
     }
```

However, I cannot use any of the classes included in the jar in my libraries. Any help?

**Comment by crowjdh** [comment]
You don't need to include jar file if you're trying to use this project. That jar file is for Java project.
1. If you're using Andorid Studio: Clone this repo and include the project into your project as a module.
2. If you're using Eclipse: Clone this repo and import the project into your eclipse workspace and add that project into your project as a library project.

If you need help, feel free to leave comment :)
